### ISSUE TITLE
Once downloading a new mod has finished, it reloads all the other mods and extends the list.

### ISSUE THREAD

**Issue by whitetxt** [Inferno-Dev-Team/Inferno-Omnia#2]
The list doesnt get cleared but it is extended anyways after reloading the other mod info.
![Extended list](https://user-images.githubusercontent.com/54776821/107947739-b8b56e00-6f8a-11eb-88c0-9549cd0560ad.png)

**Comment by MatthewOGuerra** [comment]
I see, I will fix this shortly, thank you for bringing this to my attention.

**Comment by MatthewOGuerra** [comment]
Fixed and will be pushed with 1.2.6, thank you.
